INCLUDES += -I$(SUPPORT_DIR)

C_SUPPORT_SOURCES = $(SUPPORT_DIR)main.c
C_SUPPORT_OBJECTS = $(C_SUPPORT_SOURCES:.c=.o)

$(C_SUPPORT_OBJECTS): $(C_SUPPORT_SOURCES)
	$(CC) $(SAN) $(CFLAGS) $(INCLUDES) -c $(@:.o=.c) -o $@